### ISSUE TITLE
File doesn't exist error when output file has "?"

### ISSUE THREAD

**Issue by sirlancelot** [shama/gulp-webpack#22]
I have a webpack configuration that writes the hash as a querystring for all chunks to be used as a cache-buster like so:

    module.exports = {
        entry: "index.js",
        output: {
            chunkFilename: "chunks/chunk.[id].js?[hash]
        }
    }

This setup works when using `webpack` directly; the files are emitted without the querystring and the `requireEnsure()` contains the hash.

However, when I switched to `gulp-webpack`, I get an error:

    [12:22:31] Starting 'scripts'...
    
    c:\project\node_modules\gulp-webpack\node_modules\memory-fs\lib\MemoryFileSystem.js:82
                            throw new Error("File doesn't exists " + _path);
                                  ^
    Error: File doesn't exists /tmp/chunks/chunk.1.js?f63abfa80e027b171a35
        at MemoryFileSystem.readFileSync (c:\project\node_modules\gulp-webpack\node_modules\memory-fs\lib\MemoryFileSystem.js:82:10)
        at module.exports (c:\project\node_modules\gulp-webpack\index.js:107:29)
        at Array.forEach (native)
        at Tapable.module.exports (c:\project\node_modules\gulp-webpack\index.js:104:39)
        at Tapable.applyPluginsAsync (c:\project\node_modules\webpack\node_modules\tapable\lib\Tapable.js:73:13)
        at Tapable.afterEmit (c:\project\node_modules\webpack\lib\Compiler.js:267:8)
        at Tapable.Compiler.emitAssets (c:\project\node_modules\webpack\lib\Compiler.js:262:14)
        at done (c:\project\node_modules\webpack\node_modules\async\lib\async.js:135:19)
        at _toString (c:\project\node_modules\webpack\node_modules\async\lib\async.js:32:16)
        at MemoryFileSystem.writeFile (c:\project\node_modules\gulp-webpack\node_modules\memory-fs\lib\MemoryFileSystem.js:220:9)

It looks like the memory-fs module is trying to locate the file with the querystring appended.

**Comment by shama** [comment]
@sirlancelot Have you been able to fix this?

**Comment by sirlancelot** [comment]
I haven't been able to find a fix but I'm guessing the issue better belongs over at memory-fs. I've since found a different way to classify my chunks without requiring a querystring and so I've just avoided the bug.

**Comment by raphaelluchini** [comment]
I'm getting the same problem :(
