### ISSUE TITLE
Poor error reporting on non-existent source file

### ISSUE THREAD

**Issue by joepie91** [shama/gulp-webpack#38]
Using the following code...

```javascript
gulp.task('webpack', function(){
	return gulp.src("lib-client/index.cofee")
		.pipe(webpack({
			watch: true,
			module: {
				loaders: [{ test: /\.coffee$/, loader: "coffee-loader" }]
			},
			resolve: { extensions: ["", ".web.coffee", ".web.js", ".coffee", ".js"] }
		}))
		.pipe(rename("stats.js"))
		.pipe(gulp.dest("static/js/"));
});
```

... I got the following error:

```
Error: Path doesn't exist '/home/sven/projects/cdn/412d142f659f7fef34e4.js'
  at MemoryFileSystem.writeFileSync (/home/sven/projects/cdn/node_modules/gulp-webpack/node_modules/memory-fs/lib/MemoryFileSystem.js:176:10)
  at MemoryFileSystem.writeFile (/home/sven/projects/cdn/node_modules/gulp-webpack/node_modules/memory-fs/lib/MemoryFileSystem.js:221:8)
  at Tapable.writeOut (/home/sven/projects/cdn/node_modules/gulp-webpack/node_modules/webpack/lib/Compiler.js:256:27)
  at Tapable.<anonymous> (/home/sven/projects/cdn/node_modules/gulp-webpack/node_modules/webpack/lib/Compiler.js:242:20)
  at /home/sven/projects/cdn/node_modules/gulp-webpack/node_modules/webpack/node_modules/async/lib/async.js:125:13
  at Array.forEach (native)
  at _each (/home/sven/projects/cdn/node_modules/gulp-webpack/node_modules/webpack/node_modules/async/lib/async.js:46:24)
  at Object.async.each (/home/sven/projects/cdn/node_modules/gulp-webpack/node_modules/webpack/node_modules/async/lib/async.js:124:9)
  at Tapable.emitFiles (/home/sven/projects/cdn/node_modules/gulp-webpack/node_modules/webpack/lib/Compiler.js:231:20)
  at /home/sven/projects/cdn/node_modules/gulp-webpack/node_modules/webpack/node_modules/mkdirp/index.js:47:26
  at Object.oncomplete (fs.js:107:15)
```

After way too much time debugging, I found out that I'd accidentally typed `.cofee` for my source file instead of `.coffee`, and this was making the build fail - however, there's no indication of this in the error whatsoever (which instead points at a non-existent file path, presumably in the virtual in-memory filesystem).

There should probably be a clearer error message here, indicating that no valid source file was specified or something along those lines.

**Comment by jeffscottward** [comment]
There is no real way arround this other than a suggest in the log
'Do all files references in your config match the actual filenames - this is often the cause'
