### ISSUE TITLE
Issue with empty source streams

### ISSUE THREAD

**Issue by orlandohohmeier** [shama/gulp-webpack#55]
I get an uhandled stream error, if the source stream is empty. This could happen, if for some circumstance the source glob pattern isn't matching any files.

## Setup

	var gulp = require('gulp');
	var webpack = require('gulp-webpack');
	var debug = require('gulp-debug');
	gulp.task('default', function() {
  		return gulp.src('path/to/nothing')
  			.pipe(debug())
    		.pipe(webpack())
    		.pipe(gulp.dest('dist/'));
	});
	
## Error

	stream.js:94
  	    throw er; // Unhandled stream error in pipe.
  	    
  	Error: Path doesn't exist '/vagrant/412d142f659f7fef34e4.js'
    at MemoryFileSystem.writeFileSync (/vagrant/node_modules/gulp-webpack/node_modules/memory-fs/lib/MemoryFileSystem.js:175:10)
    at MemoryFileSystem.writeFile (/vagrant/node_modules/gulp-webpack/node_modules/memory-fs/lib/MemoryFileSystem.js:220:8)
    at Tapable.writeOut (/vagrant/node_modules/webpack/lib/Compiler.js:258:27)
    at Tapable.<anonymous> (/vagrant/node_modules/webpack/lib/Compiler.js:244:20)
    at /vagrant/node_modules/webpack/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/vagrant/node_modules/webpack/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/vagrant/node_modules/webpack/node_modules/async/lib/async.js:124:9)
    at Tapable.emitFiles (/vagrant/node_modules/webpack/lib/Compiler.js:233:20)
    at /vagrant/node_modules/webpack/node_modules/mkdirp/index.js:47:26

## Log
	gulp-debug: 0 items

**Comment by shama** [comment]
That is expected. What did you expect to happen instead?

**Comment by orlandohohmeier** [comment]
It should raise the "no files files given" log.

**Comment by shama** [comment]
Ah ok, I'd take a patch for that. Thanks!
